-- Seed dataset: 16 realistic job/internship listings across tech categories
INSERT INTO jobs (title, company, domain, location, type, description, required_skills, nice_skills, category, salary) VALUES
('Frontend Engineer', 'Vercel', 'vercel.com', 'Remote', 'job',
 'Build the next generation of our dashboard using React, Next.js and TypeScript. You will own component architecture, performance budgets and accessibility. Deep knowledge of React hooks, server components and modern CSS (Tailwind) required.',
 '["react","typescript","next.js","css"]', '["tailwind","graphql","vercel"]', 'Frontend', '$140k - $190k'),
('Backend Engineer (Node.js)', 'Stripe', 'stripe.com', 'San Francisco, CA', 'job',
 'Design and scale payment APIs handling millions of requests per day. Strong experience with Node.js, PostgreSQL, Redis and distributed systems. You will write idempotent endpoints, optimize SQL queries and work with message queues (Kafka).',
 '["node.js","postgresql","redis","api"]', '["kafka","docker","kubernetes"]', 'Backend', '$160k - $210k'),
('Full-Stack Developer Intern', 'Shopify', 'shopify.com', 'Toronto, ON (Hybrid)', 'internship',
 'Join our storefront team for a 4-month internship. Work with React on the frontend and Ruby on Rails / Node.js services on the backend. Ship real features to millions of merchants with a dedicated mentor.',
 '["react","javascript","node.js"]', '["ruby","graphql","sql"]', 'Full-Stack', '$32/hr'),
('Machine Learning Engineer', 'Anthropic', 'anthropic.com', 'San Francisco, CA', 'job',
 'Train and evaluate large language models. Requires strong Python, PyTorch, and experience with distributed training (Ray, DeepSpeed). Familiarity with transformers, RLHF and evaluation harnesses expected.',
 '["python","pytorch","machine learning","transformers"]', '["ray","deepspeed","rlhf","cuda"]', 'ML/AI', '$200k - $300k'),
('Data Engineer', 'Airbnb', 'airbnb.com', 'Remote (US)', 'job',
 'Own batch and streaming pipelines feeding our search platform. Expert SQL, Python and Spark required. Experience with Airflow orchestration, dbt modeling and data quality frameworks.',
 '["python","sql","spark","airflow"]', '["dbt","kafka","snowflake"]', 'Data', '$150k - $200k'),
('DevOps Engineer', 'Cloudflare', 'cloudflare.com', 'Austin, TX', 'job',
 'Operate Kubernetes clusters across 300+ edge locations. Deep experience with Docker, Kubernetes, Terraform and CI/CD pipelines (GitHub Actions, ArgoCD). Prometheus/Grafana observability stack.',
 '["docker","kubernetes","terraform","ci/cd"]', '["prometheus","grafana","argocd","go"]', 'DevOps', '$145k - $185k'),
('iOS Engineer', 'Duolingo', 'duolingo.com', 'Pittsburgh, PA', 'job',
 'Craft delightful learning experiences in Swift and SwiftUI. Strong understanding of Combine, Core Data and App Store release processes. Animation chops with Lottie are a plus.',
 '["swift","swiftui","ios"]', '["combine","core data","lottie"]', 'Mobile', '$135k - $175k'),
('Android Engineer Intern', 'Spotify', 'spotify.com', 'New York, NY', 'internship',
 'Summer internship on the Android playback team. Kotlin and Jetpack Compose required. You will profile audio pipelines and contribute to our design system.',
 '["kotlin","android","jetpack compose"]', '["coroutines","exoplayer","gradle"]', 'Mobile', '$40/hr'),
('Security Engineer', 'Cloudflare', 'cloudflare.com', 'Remote', 'job',
 'Hunt threats across our edge network. Requires experience with network security, SIEM tooling, Python scripting for automation, and familiarity with zero-trust architectures and WAF rule design.',
 '["security","python","networking","siem"]', '["zero trust","waf","rust"]', 'Security', '$150k - $195k'),
('Product Designer', 'Figma', 'figma.com', 'San Francisco, CA (Hybrid)', 'job',
 'Design collaborative canvas features used by millions. Mastery of Figma (obviously), strong interaction design portfolio, prototyping skills and experience with design systems and user research.',
 '["figma","interaction design","prototyping","design systems"]', '["user research","framer","motion"]', 'Design', '$130k - $175k'),
('QA Automation Engineer', 'Atlassian', 'atlassian.com', 'Remote', 'job',
 'Build automated test infrastructure for Jira. Expert with Selenium, Cypress and Playwright. Java or TypeScript required. Experience with CI integration and flaky-test triage.',
 '["selenium","cypress","playwright","java"]', '["typescript","ci/cd","jira"]', 'QA', '$110k - $145k'),
('Data Science Intern', 'Netflix', 'netflix.com', 'Los Gatos, CA', 'internship',
 'Analyze experimentation data from the recommendation system. Strong SQL, Python (pandas), and statistics (A/B testing, hypothesis testing) required. Tableau or Looker for dashboards.',
 '["python","sql","statistics","pandas"]', '["a/b testing","tableau","looker"]', 'Data', '$45/hr'),
('Site Reliability Engineer', 'Datadog', 'datadoghq.com', 'New York, NY', 'job',
 'Keep our metrics platform running at planet scale. Linux internals, Kubernetes, Go or Python for tooling, incident response and capacity planning. On-call rotation.',
 '["kubernetes","linux","go","sre"]', '["python","terraform","prometheus"]', 'DevOps', '$155k - $200k'),
('AI Research Intern', 'Hugging Face', 'huggingface.co', 'Remote', 'internship',
 'Contribute to open-source model evaluation. Python, PyTorch and the transformers library required. Experience fine-tuning LLMs (LoRA) and writing evaluation benchmarks is a big plus.',
 '["python","pytorch","transformers","llm"]', '["lora","fine-tuning","huggingface"]', 'ML/AI', '$50/hr'),
('Platform Engineer (Go)', 'HashiCorp', 'hashicorp.com', 'Remote', 'job',
 'Build Terraform Cloud control plane services in Go. gRPC APIs, PostgreSQL persistence, distributed consensus (Raft). Experience with cloud providers (AWS, GCP) essential.',
 '["go","grpc","postgresql","aws"]', '["raft","terraform","gcp"]', 'Backend', '$150k - $195k'),
('Marketing Growth Analyst', 'Notion', 'notion.so', 'San Francisco, CA', 'job',
 'Drive top-of-funnel growth experiments. SQL proficiency, experience with Google Analytics, Amplitude and SEO tooling. Python for analysis automation is a plus.',
 '["sql","google analytics","seo","amplitude"]', '["python","looker","dbt"]', 'Marketing', '$95k - $130k');

-- Demo user (free plan) for immediate testing
INSERT INTO users (email, name, plan) VALUES ('demo@jobfinder.ai', 'Demo Candidate', 'free');
